# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 355447000-md-taco
  namespace: 355447e3
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: tks
