# Source: cluster-api-byoh/templates/byoh-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 3.55447e+08-control-plane
  namespace: 355447e3
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: control-plane
